### PR TITLE
argument parsing changes

### PR DESCRIPTION
**Pull request by austin-ralls-cs**
First commit cleans up code without changing output much (will help with tab completion), second commit fixes bug, and third commit changes output (in a good way imo but lmk what you think)

Close https://github.com/CarveSystems/scanamabob/issues/22

### CODE REVIEW

**Comment by meadori-cs** [comment]
b336e46  looks "correct", but the output is noticeably different than before.  In particular:

*before*

```
scanamabob
Usage: scanamabob <command> [-h] [command-specific-arguments]

Scanamabob v0.0.2 - AWS Security Tooling

This tool is in a very early phase of development and is undergoing active development. Many desired features are currently missing and incomplete. Early release of this version through PyPI is intended to generate useful feedback from potential users.

  scan     -  Scan AWS environment for common security misconfigurations
  s3audit  -  Generate report on S3 access controls
```

*after*

```
scanamabob
usage: Usage: scanamabob <command> [command-specific-arguments]
scanamabob: error: the following arguments are required: command
```

*before*

```
scanamabob -h
Usage: scanamabob <command> [-h] [command-specific-arguments]

Scanamabob v0.0.2 - AWS Security Tooling

This tool is in a very early phase of development and is undergoing active development. Many desired features are currently missing and incomplete. Early release of this version through PyPI is intended to generate useful feedback from potential users.

  scan     -  Scan AWS environment for common security misconfigurations
  s3audit  -  Generate report on S3 access controls
```

*after*

```
scanamabob -h
usage: Usage: scanamabob <command> [command-specific-arguments]

Scanamabob v0.0.2 - AWS Security Tooling

This tool is in a very early phase of development and is undergoing active development. Many desired features are currently missing and incomplete. Early release of this version through PyPI is intended to generate useful feedback from potential users.

positional arguments:
  {s3audit,scan,summary}

optional arguments:
  -h, --help            show this help message and exit
```

I am fine with the difference, but I will let @CarveKenneth comment.

**Comment by meadori-cs** [comment]
Everything else LGTM.

**Comment by CarveKenneth** [comment]
hmm... i'd like it to show you that there is a `-h` or `--help` option when you invoke the program with no arguments, but I could give that up if it requires a wonky implementation to add it since that flag is generally expected to be there anyway.

I also intentionally wanted the `-h` output to give some light descriptions of what the commands do, which was why i replaced the autogenerated help block with the hand-written one. 

Is there a way to replace
```
positional arguments:
  {s3audit,scan,summary}
```
with something that helps a user understand what those commands do?

**Comment by austin-ralls-cs** [comment]
Yeah, I just forgot to move the subcommand help messages. Fixed in https://github.com/CarveSystems/scanamabob/pull/44/commits/563bed24abbd32ef3834b78b548b50f67e9784af

I did intentionally not print the full help message when running the program as a personal preference and because that's the argparse default, but I added that back in in https://github.com/CarveSystems/scanamabob/pull/44/commits/80012b81ad3236093c000e730fb5535bac6dec4f

**Pull request merged**
